spring.application.name=REVHIRE_P2

# Oracle DB Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8081

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging (Log4j2 via Spring Boot starter)
logging.level.org.springframework.web=INFO
logging.level.com.rev.app=DEBUG

# File Upload configuration
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
